service: hotweiler

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  region: us-east-1
  environment:
    COGNITO_USER_POOL_ID:
      Ref: CognitoUserPool
  apiGateway:
    apiKeys:
        - name: pwaApiKey

functions:
  ai-chat:
    handler: application/handler.talk
    events:
      - http:
          path: ai/chat/talk
          method: post
          cors: true
          private: true
          authorizer:
            arn: "arn:aws:cognito-idp:${self:provider.region}:${env:AWS_ACCOUNT_ID}:userpool/${env:AWS_USER_POOL_ID}"
          
resources:
  Resources:
    CognitoUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: HotweilerUserPool
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        ClientName: HotweilerUserPoolClient
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 3000