service: hotweiler

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-1
  environment:
    COGNITO_USER_POOL_ID:
      Ref: CognitoUserPool
  apiGateway:
    apiKeys:
        - name: pwaApiKey

functions:
  ai-chat:
    handler: handler.hello
    events:
      - http:
          path: ai/chat
          method: post
          cors: true
          private: true
          authorizer:
            arn: 
              Fn::Join:
                - ''
                - - 'arn:aws:cognito-idp:'
                  - Ref: 'AWS::Region'
                  - ':'
                  - Ref: 'AWS::AccountId'
                  - ':userpool/'
                  - Ref: CognitoUserPool
          
resources:
  Resources:
    CognitoUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: HotweilerUserPool
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        ClientName: HotweilerUserPoolClient
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH