service: hotweiler

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-1
  apiKeys:
    - pwaApiKey

functions:
  ai-chat:
    handler: handler.hello
    events:
      - http:
          path: ai/chat
          method: post
          cors: true
          private: true
          
resources:
  Resources:
    CognitoUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: HotweilerUserPool
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        ClientName: HotweilerUserPoolClient
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH